export interface IImgParams {
  src: string;
  width: number;
  height: number;
}

export const IMG_PROPERTIES = {
  defaultImgBlur:
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAOGVYSWZNTQAqAAAACAABh2kABAAAAAEAAAAaAAAAAAACoAIABAAAAAEAAAGQoAMABAAAAAEAAAGQAAAAADj5TfYAAAE7SURBVHicBcG7TsJQAADQPm5bKVJeBauIVSoDDU7EGCcT4+DO5uyn6Q+4InFxwEjUEAgYCiIiSrV4gT5u356DV6rVCOYvtKVFR0yM9F3PB8D4UgPHxcIQZOPscSFt6+YA2n1oFwubsd3cTe1Zn0GaAmDcGZ4K1OXF2WAKa+0Jn4xMfHenJE4wwvudE2tbwm1n9vCkiDvC+aFkGajeUOgwLAssY6yId2U6puJXLfX6rr3wwp5qLpDn/Gjan5mtHIBcRXYw4tvFH5e+B/0NWTrhU7MPNSkKI4iAWMxjCA2G02hiXXd8KcNJUXLCYLOVo3UV0K035PKeLAnK61uXInGUaN2/aCrMchRpIwANu9nsMYGLSAZx/H4pb/CppabbcyuIsDhfPiKxQLec9HYWGi7I8DRLxvCAo6lR//MfpeiioWAfaIwAAAAASUVORK5CYII=',
};

// export const DEFAULT_ARTICLE_LOGO_NAME = 'zastavka.jpg';
// export const DEFAULT_ARTICLE_LOGO_PATH = `/Images/channelsOptimized/${DEFAULT_ARTICLE_LOGO_NAME}`;
